#!/usr/bin/perl
use WebService::Discord::Webhook;
use POSIX qw(strftime);
use File::Slurp;

my $HookFile = "/root/.MyHook.txt";
my $MyWebHook = read_file($HookFile);
chop($MyWebHook);
my $webhook = WebService::Discord::Webhook->new($MyWebHook);

if (! -f $HookFile)
{
	print "$HookFile not found - please paste the webhook in it and run this again\n";
	exit (0);
}

#my $UserOutputCmd = "echo country \\* |/home/empowner/empire/bin/empire POGO admin";
# NewsCommand
my $NewsCmd = "echo news |/home/empowner/empire/bin/empire visitor visitor";
# Power Command
my $PowerCmd = "echo power |/home/empowner/empire/bin/empire visitor visitor";
my $NewsFile = "/var/www/html/news.txt";
my $PowerFile = "/var/www/html/power.txt";
my @InputLines = ();

@InputLines = `$NewsCmd`;

open(FH, '>', $NewsFile) or die $!;

my $CurLine = 0;
my $MaxLine = 0;
foreach (@InputLines)
{
	$MaxLine++;
}
$MaxLine -= 3;
foreach (@InputLines)
{
	if (($CurLine > 4) && ($CurLine <= $MaxLine))
	{
		print FH $_;
	}
	$CurLine++;
}
close (FH);

open(FH, '>', $PowerFile) or die $!;
@InputLines = `$PowerCmd`;

my $CurLine = 0;
my $MaxLine = 0;
foreach (@InputLines)
{
	$MaxLine++;
}
$MaxLine -= 4;
foreach (@InputLines)
{
	if (($CurLine > 2) && ($CurLine <= $MaxLine))
	{
		print FH $_;
	}
	$CurLine++;
}
close (FH);

my $CurDate = strftime "%m/%d/%Y", localtime;
$webhook->get();
print "Webhook posting as '" . $webhook->{name} .
  "' in channel " . $webhook->{channel_id} . "\n";
my $file_content = read_file($NewsFile); 
chop($file_content);
$webhook->execute( content => "News Report - $CurDate", file => {name => "News.txt", data =>"$file_content"});


# Now handle power report
@InputLines = `$PowerCmd`;

open(FH, '>', $PowerFile) or die $!;

$CurLine = 0;
$MaxLine = 0;
foreach (@InputLines)
{
	$MaxLine++;
}
$MaxLine -= 3;
foreach (@InputLines)
{
	if (($CurLine > 4) && ($CurLine <= $MaxLine))
	{
		print FH $_;
	}
	$CurLine++;
}
close (FH);
$file_content = read_file($PowerFile); 
chop($file_content);
$webhook->execute( content => "Power Report - $CurDate", file => {name => "Power.txt", data =>"$file_content"});


exit 0; 
